export interface StartQuizRequest {
  topic: string
  student_id?: string
  difficulty?: number
}

export interface StartQuizResponse {
  session_id: string
  student_id: string   // generated by backend when not supplied
  question: string
  difficulty: number
}

export interface AnswerRequest {
  session_id: string
  student_id: string
  answer: string
}

export interface AnswerResponse {
  correct: boolean
  explanation: string
  feedback: string
  next_question: string
  difficulty: number
  score: number         // cumulative score (computed client-side; backend returns streak)
  streak: number
  next_action: string   // "escalate" | "scaffold" | "same"
}

// Stored locally for the results screen
export interface HistoryEntry {
  question: string
  answer: string
  correct: boolean
  difficulty: number
}

export interface QuizSession {
  session_id: string
  student_id: string
  topic: string
  score: number
  streak: number
  difficulty: number
  history: HistoryEntry[]
}
